development: 

  secret_key_base: sk_test_UNk9i7hx6ZHwmpYbLd3J0ntW00LVPQ9Hku
  stripe_publishable_key: pk_test_BISbtL5ftfrBcOCyvmNxTWHx00KJ8ezaWM
  stripe_secret_key: sk_test_UNk9i7hx6ZHwmpYbLd3J0ntW00LVPQ9Hku

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']